
language: android    

jdk:
  - openjdk8

android:
  components:
    - tools
    - tools
    - build-tools-29.0.2
    - platform-tools
    - android-28

script:
  ./gradlew clean build jacocoTestReport --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
